from __future__ import annotations

from typing import Any


ANALYSIS_HINTS: tuple[dict[str, Any], ...] = (
    {
        "id": "traffic-http-webshell-delimited-flag",
        "title": "HTTP webshell delimited flag output",
        "category": "traffic",
        "status": "solver_supported",
        "signals": [
            "HTTP traffic posts to a shell-like path such as /shell.php",
            "Responses wrap command output in delimiters such as X@Y, [S], [E], or cwd lines",
            "A generic flag{...} marker appears immediately after wrapper bytes",
        ],
        "recommended_steps": [
            "Decode tshark HTTP file_data hex and transform candidates",
            "Export HTTP objects and inspect small shell response bodies",
            "Extract embedded generic flag markers even when they are adjacent to delimiter text",
        ],
        "solver_paths": ["TrafficSolver.decoded_http_artifacts", "TrafficSolver.http_object_exports"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "traffic-data-uri-image",
        "title": "Raw TCP data URI image",
        "category": "traffic",
        "status": "solver_supported",
        "signals": [
            "PCAP contains raw TCP payloads with data:image/*;base64,",
            "HTTP object export is empty or incomplete",
        ],
        "recommended_steps": [
            "Follow shortlisted TCP streams",
            "Extract and hash decoded image bytes",
            "Inspect exported image for visual flags",
        ],
        "solver_paths": ["TrafficSolver.data_uri_artifacts"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "traffic-raw-capture-flag-scan",
        "title": "Bounded raw PCAP flag scan",
        "category": "traffic",
        "status": "solver_supported",
        "signals": [
            "PCAP bytes contain a printable CTF flag marker",
            "tshark field extraction or HTTP object export is empty or incomplete",
        ],
        "recommended_steps": [
            "Scan only a bounded byte prefix before heavier carving",
            "Preserve bytes_scanned and truncated evidence",
            "Escalate to stream/object reconstruction if the bounded prefix misses",
        ],
        "solver_paths": ["TrafficSolver.raw_capture_flag_scan"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "traffic-pcap-resync-ip-id-stego",
        "title": "Corrupt PCAP resync plus IP-ID stego",
        "category": "traffic",
        "status": "solver_supported",
        "signals": [
            "tshark reports a damaged PCAP record length such as packet bigger than maximum",
            "Only the first few frames parse even though raw bytes contain later HTTP or TCP clues",
            "Repeated short TCP payloads ask where the flag is, often to an unusual local port",
        ],
        "recommended_steps": [
            "Resynchronize classic PCAP record headers and write a repaired capture artifact",
            "Collect IPv4 Identification values from marker payload packets",
            "Decode adjacent-deduped IP-ID words as little-endian byte pairs and scan for flags",
        ],
        "solver_paths": ["TrafficSolver.pcap_record_resync", "TrafficSolver.ip_id_stego"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "traffic-rf-image-manchester-ask",
        "title": "RF image ASK/OOK Manchester",
        "category": "traffic",
        "status": "solver_supported",
        "signals": [
            "Attachment is a PNG/JPG waveform rather than a packet capture",
            "Prompt mentions RF, radio, ASK, OOK, Manchester, sine, or waveform",
        ],
        "recommended_steps": [
            "Extract the colored waveform trace from the image",
            "Estimate carrier period and search half-bit Manchester timing",
            "Decode both Manchester polarities and preserve timing evidence",
        ],
        "solver_paths": ["TrafficSolver.rf_image_waveform"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "forensics-registry-wifi",
        "title": "Windows registry WiFi SSID",
        "category": "forensics",
        "status": "solver_supported",
        "signals": [
            "UTF-16LE .reg export",
            "NetworkList\\Nla\\Wireless and NetworkList\\Profiles entries",
        ],
        "recommended_steps": [
            "Decode SSID hex values",
            "Cross-check profile names",
            "Normalize flag format by removing spaces when required",
        ],
        "solver_paths": ["ForensicsSolver.registry_wifi"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "forensics-vmdk-bitlocker-fvestats",
        "title": "VMDK carved RegistryBackup BitLocker timeline",
        "category": "forensics",
        "status": "solver_supported",
        "signals": [
            "Attachment is a VMware VMDK or raw disk image",
            "Carving reveals RegistryBackup with SYSTEM/SAM/SOFTWARE hives",
            "Question asks for BitLocker encryption start and finish time",
        ],
        "recommended_steps": [
            "Carve embedded zip archives or inspect foremost-output/zip",
            "Read SYSTEM\\ControlSet001\\Control\\FVEStats",
            "Convert OsvEncryptInit and OsvEncryptComplete FILETIME values to UTC+8",
        ],
        "solver_paths": ["ForensicsSolver.registry_bitlocker_fvestats", "scripts/solve_babybit_vmdk.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "forensics-bmp-quickstego-braille",
        "title": "BMP QuickStego hex to Braille",
        "category": "forensics",
        "status": "solver_supported_with_manual_quickstego_fallback",
        "signals": [
            "BMP appears structurally clean",
            "Prompt hints at Windows tooling, light, eyes, or Braille",
            "Recovered payload is long hex but not normal UTF-8",
        ],
        "recommended_steps": [
            "Try ForgeFlag BMP LSB candidates and QuickStego if needed",
            "Convert recovered hex to binary without leading-zero padding",
            "Split into 6-bit Braille ASCII and normalize markers",
        ],
        "solver_paths": ["image_stego.lsb_candidates", "transform.hex_braille_ascii_normalize"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "forensics-visual-crypto-xor",
        "title": "1-bit visual cryptography shares",
        "category": "forensics",
        "status": "manual_replay_script",
        "signals": [
            "Two or more black-white/noise-like image shares",
            "Prompt references battle, overlay, or visual cipher",
        ],
        "recommended_steps": [
            "Verify image dimensions match",
            "XOR or difference the shares",
            "Read visible ciphertext or scene text from the revealed image",
        ],
        "solver_paths": ["scripts/solve_battle_visual_cipher.py"],
        "docs": ["docs/ctf-casebook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "forensics-osint-building-geolocation",
        "title": "OSINT building geolocation",
        "category": "forensics",
        "status": "manual_replay_script",
        "signals": [
            "Prompt asks which building a photo was taken from",
            "Image contains skyline, bridge, hotel, billboard, or street-view landmarks",
            "Challenge accepts a case-insensitive building name inside the flag wrapper",
        ],
        "recommended_steps": [
            "Preserve image hash and visible landmark observations before naming the building",
            "Use official writeup or scoped OSINT notes as replay evidence rather than only the final flag",
            "Normalize the building name to lowercase underscores inside the challenge flag wrapper",
        ],
        "solver_paths": ["scripts/solve_ductf_osint_building.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "forensics-osint-music-cross-reference",
        "title": "OSINT music cross-reference",
        "category": "forensics",
        "status": "manual_replay_script",
        "signals": [
            "Prompt mentions a musician, composer, soundtrack, or artist rather than only a place",
            "The visible image is a location clue but the flag format asks for a normalized name",
            "Challenge context includes franchise or media-specific vocabulary such as Dune spice or stillsuit",
        ],
        "recommended_steps": [
            "Strip README/challenge flag oracle lines before deriving the answer",
            "Cross-reference prompt composer/media clues against public soundtrack or artist evidence",
            "Normalize the musician or track name with underscores inside the platform flag wrapper",
        ],
        "solver_paths": ["scripts/solve_hans_zimmer_osint.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "crypto-shifted-rsa-factor-leak",
        "title": "Shifted RSA factor leak",
        "category": "crypto",
        "status": "manual_replay_script",
        "signals": [
            "Service prints RSA ciphertext and modulus before asking for a password",
            "A later branch leaks a value shaped like (p - s) * (q - s)",
            "The shift s is generated from a small random bit bound",
        ],
        "recommended_steps": [
            "Parse c, n, and the shifted product from the local/authorized transcript",
            "Enumerate the small shift and solve p + q = (n + s*s - leak) / s",
            "Decrypt the password and submit it back to the same challenge service",
        ],
        "solver_paths": ["scripts/solve_accountleak.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "crypto-rsa-modular-low-exponent-root",
        "title": "RSA modular low-exponent root",
        "category": "crypto",
        "status": "solver_supported",
        "signals": [
            "Source imports iroot or gmpy2 and loops over a small range",
            "The check is shaped like iroot(c+n*i,e) or iroot(c+i*n,e)",
            "The script prints long_to_bytes(root) after an exact-root test",
        ],
        "recommended_steps": [
            "Extract n and c from the local challenge source",
            "Infer e from the iroot call and preserve the range(...) bound as root_search_limit",
            "Search for k where c + k*n is an exact e-th power, then convert the root to bytes",
        ],
        "solver_paths": ["forgeflag.crypto_analysis.recover_rsa_flags_from_text"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "crypto-lfsr-berlekamp-massey",
        "title": "LFSR Berlekamp-Massey recovery",
        "category": "crypto",
        "status": "solver_supported",
        "signals": [
            "Source defines class lfsr with init, mask, and parity feedback",
            "A long 0/1 output sequence is embedded in a comment or output file",
            "The flag is derived from sha256(hex(KEY)[2:]) or another key hash",
        ],
        "recommended_steps": [
            "Parse the output bit sequence and LFSR length from the local challenge source",
            "Build GF(2) linear equations for the mask and enumerate any remaining free variables",
            "Recover the initial key, replay the LFSR output, and filter candidates with the provided hash prefix",
        ],
        "solver_paths": ["forgeflag.crypto_analysis.recover_lfsr_bm_flags_from_text"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "crypto-prng-stream-replay",
        "title": "PRNG and stream-cipher replay",
        "category": "crypto",
        "status": "solver_supported",
        "signals": [
            "Python source uses random.seed/getrandbits, LCG recurrence, LFSR taps, or MT19937 outputs",
            "Comments or sidecar files contain consecutive generator outputs, ciphertext, seed high bits, or key observations",
            "The first obvious flag-like string is in source and needs replay evidence before acceptance",
        ],
        "recommended_steps": [
            "Prefer deterministic replay before generic transform decoding or hash triage",
            "For LCG, use known a/b/n, derive b from two outputs, derive n from six outputs, or lift residues with flag grammar",
            "For LFSR and MT19937, preserve taps/seed leaks, clone full 624-output MT state, and document missing key/output artifacts separately",
        ],
        "solver_paths": ["CryptoSolver.prng_stream", "scripts/solve_prng_stream_cipher_cases.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "crypto-debruijn-pin-replay",
        "title": "De Bruijn PIN replay",
        "category": "crypto",
        "status": "manual_replay_script",
        "signals": [
            "Local service asks for repeated short PIN guesses over a fixed alphabet",
            "The verifier keeps a sliding window over submitted digits",
            "The attempt budget is near alphabet_size ** pin_length",
        ],
        "recommended_steps": [
            "Generate a De Bruijn sequence covering every fixed-length PIN window",
            "Match the service's input direction before submitting the attempt stream",
            "Replay against the same local/authorized challenge service and preserve the transcript flag",
        ],
        "solver_paths": ["scripts/solve_accessible_sesamum.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "crypto-chacha-state-keystream",
        "title": "ChaCha state-as-keystream",
        "category": "crypto",
        "status": "manual_replay_script",
        "signals": [
            "Challenge claims ChaCha or Salsa but serializes the current state directly as keystream",
            "Chosen plaintext encryption is available before encrypting the flag",
            "The state update happens after a buffer is produced from the current state",
        ],
        "recommended_steps": [
            "Encrypt one full known-plaintext block to recover the serialized state",
            "Run the provided block function locally to compute the next state buffer",
            "XOR the encrypted flag with the predicted next buffer and preserve transcript evidence",
        ],
        "solver_paths": ["scripts/solve_babycha.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "crypto-composite-ntru-crt-lattice",
        "title": "Composite-ring NTRU CRT lattice",
        "category": "crypto",
        "status": "manual_replay_script",
        "signals": [
            "Sage challenge defines an NTRU-like ring modulo x^N - 1 with composite N",
            "Public key has the shape p * f_q^-1 * g and ciphertext is b * pub + msg",
            "Output includes public key and ciphertext coefficient lists",
        ],
        "recommended_steps": [
            "Factor x^N - 1 into smaller CRT components",
            "Run lattice reduction on each component to recover short key residues",
            "Recombine residues, test cyclic shifts, and decrypt the binary message polynomial",
        ],
        "solver_paths": ["scripts/solve_giedi_composite.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "forensics-archive-mangled-png",
        "title": "Archive entry with mangled PNG signature",
        "category": "forensics",
        "status": "solver_supported_with_visual_followup",
        "signals": [
            "Container extension lies, such as .pdf that is a ZIP archive",
            "Inner entry is named .png but starts with non-PNG bytes followed by IHDR",
        ],
        "recommended_steps": [
            "Extract the small archive entry into the managed artifact workspace",
            "Repair the PNG signature when the chunk structure is intact",
            "Run image text/stego analysis, then preserve visual/OCR or human transcription for handwritten flags",
        ],
        "solver_paths": ["ForensicsSolver.archive_image_recoveries", "scripts/solve_filefactory.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "forensics-minecraft-region-orphan",
        "title": "Minecraft region orphan chunk lore",
        "category": "forensics",
        "status": "solver_supported",
        "signals": [
            "Attachment is a .mca or .mcr Minecraft region file",
            "Challenge mentions Minecraft, a chest, missing items, or coordinates",
            "Current chunk state is empty but old sector data may remain",
        ],
        "recommended_steps": [
            "Decode Anvil region sectors with zlib/gzip chunk compression",
            "Scan both header-referenced chunks and orphan sectors",
            "Join short JSON text lore fragments and verify the recovered flag",
        ],
        "solver_paths": ["ForensicsSolver.minecraft_region"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "web-renderer-dns-rebinding",
        "title": "Renderer SSRF DNS rebinding",
        "category": "web",
        "status": "manual_replay_script",
        "signals": [
            "URL-to-PDF or URL-to-screenshot renderer",
            "Preflight DNS validation differs from renderer fetch",
        ],
        "recommended_steps": [
            "Confirm local or authorized challenge scope",
            "Use a rebinding hostname only against the challenge target",
            "Preserve fetched PDF or rendered artifact as replay evidence",
        ],
        "solver_paths": ["scripts/solve_reportlab.py"],
        "docs": ["docs/ctf-casebook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "web-basic-auth-prefix-strcmp",
        "title": "Basic Auth prefix strcmp",
        "category": "web",
        "status": "manual_replay_script",
        "signals": [
            "C source compares credentials with strncmp(s1, s2, strlen(s1))",
            "Credentials are generated as hex strings or otherwise brute-forceable by prefix",
            "HTTP Basic Auth is parsed manually before serving flag.txt",
        ],
        "recommended_steps": [
            "Compile the local challenge source or start the local service",
            "Brute force one-character credential prefixes under the allowed alphabet",
            "Preserve the HTTP response and returned flag as replay evidence",
        ],
        "solver_paths": ["scripts/solve_cecure_cerver.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "web-php-pack-procfs",
        "title": "PHP pack token to procfs",
        "category": "web",
        "status": "manual_replay_script",
        "signals": [
            "PHP service uses pack() with a user-controlled format string",
            "Token data is signed but later unpacked into a permissions integer",
            "Path joins a fixed /pro or /basic root with user-controlled suffixes",
        ],
        "recommended_steps": [
            "Use X format rewind operators to overwrite the packed permissions integer",
            "Request the pro path suffix that joins into /proc/self/root/flag.txt",
            "Replay against a local Docker service and preserve token, path, and HTTP response evidence",
        ],
        "solver_paths": ["scripts/solve_private_hidden_paths.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "web-loopback-alias-ssrf",
        "title": "Loopback alias SSRF",
        "category": "web",
        "status": "manual_replay_script",
        "signals": [
            "Source blocks localhost or 127.0.0.1 by substring before server-side fetch",
            "A local-only route checks req.ip for loopback addresses",
            "The fetch target can use another 127.0.0.0/8 address such as 127.0.0.2",
        ],
        "recommended_steps": [
            "Confirm the target is a local or explicitly authorized CTF service",
            "POST a URL using a loopback alias that bypasses the source blacklist",
            "Preserve the source filter, SSRF URL, local route evidence, and returned flag",
        ],
        "solver_paths": ["scripts/solve_fetcher.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "web-python-class-pollution",
        "title": "Python class pollution",
        "category": "web",
        "status": "manual_replay_script",
        "signals": [
            "Python source recursively merges user JSON into an object with setattr",
            "The merge accepts nested keys such as __class__, __init__, or __globals__",
            "A route decision depends on a module global or class-level variable",
        ],
        "recommended_steps": [
            "Authenticate only against the local or authorized challenge service",
            "Submit a nested JSON payload that writes through __class__.__init__.__globals__",
            "Preserve the merge sink, pollution path, and protected route response",
        ],
        "solver_paths": ["scripts/solve_co2.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "web-h3-h1-request-smuggling",
        "title": "HTTP/3 to H1 smuggling",
        "category": "web",
        "status": "manual_replay_script",
        "signals": [
            "Reverse proxy converts HTTP/3 or HTTP/2 requests into HTTP/1.1 bytes",
            "Proxy preserves Transfer-Encoding while also forwarding attacker-controlled body bytes",
            "Backend exposes an internal route that the front proxy blocks directly",
        ],
        "recommended_steps": [
            "Reconstruct the exact HTTP/1.1 bytes produced by the proxy",
            "Use a zero-length chunk followed by a second backend request",
            "Replay against a local backend and preserve the converted request bytes plus protected response",
        ],
        "solver_paths": ["scripts/solve_http_fanatics.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "web-lamenote-substring-oracle",
        "title": "Iframe-gated note search oracle",
        "category": "web",
        "status": "manual_replay_script",
        "signals": [
            "Source-attached note app requires Sec-Fetch-Dest: iframe before serving routes",
            "Search checks whether the query is a substring of owner-scoped note titles or text",
            "A single search result renders the note with dynamic image CSP derived from note data",
        ],
        "recommended_steps": [
            "Inspect /search and the iframe sandbox/CSP boundary in the local challenge source",
            "Treat admin-only note text as a prefix substring oracle only under local or authorized CTF scope",
            "When no live adminbot flag is shipped, preserve a source-pattern replay and manifest flag pattern evidence",
        ],
        "solver_paths": ["scripts/solve_lamenote.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "crypto-python-random-prime-offset",
        "title": "Python random prime offset",
        "category": "crypto",
        "status": "solver_supported",
        "signals": [
            "Python source prints gift = key[i] ^ seed[i]",
            "random.seed(bytes_to_long(seed)) drives next_prime(random.randint(...)) offsets",
            "Output is bytes_to_long(flag) plus or minus those random prime offsets",
        ],
        "recommended_steps": [
            "Recover seed bytes from key XOR gift",
            "Replay Python random with bytes_to_long(seed) and regenerate the prime offsets",
            "Remove the t-r offset from the output integer and convert back to bytes",
        ],
        "solver_paths": ["CryptoSolver.python_random_prime_offset"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "crypto-linear-xorshift-inverse",
        "title": "Linear right-shift XOR inverse",
        "category": "crypto",
        "status": "solver_supported",
        "signals": [
            "Python script seeds random deterministically before encryption",
            "Encryption repeatedly applies ct ^= ct >> random.randint(a, b)",
            "An assert compares enc(flag) to a bytes literal",
        ],
        "recommended_steps": [
            "Recreate the shift sequence from the deterministic seed",
            "Apply inverse x ^= x >> k steps in reverse order over the fixed flag bit length",
            "Decode the recovered bytes and preserve seed, rounds, and ciphertext evidence",
        ],
        "solver_paths": ["CryptoSolver.linear_xorshift"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "misc-recipe-state",
        "title": "Recipe state puzzle",
        "category": "misc",
        "status": "solver_supported",
        "signals": [
            "Prompt or title describes cooking, bowls, ingredients, or serving",
            "Attachment has repeated quantity and ingredient operations",
            "Expected answer is a small ingredient phrase",
        ],
        "recommended_steps": [
            "Model bowl operations as state updates",
            "Represent final dish as linear expressions over ingredients",
            "Brute force tiny quantity domains and wrap the recovered phrase",
        ],
        "solver_paths": ["MiscSolver.recipe_state"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "misc-decayed-doublehelix-ruby",
        "title": "Decayed DoubleHelix Ruby source",
        "category": "misc",
        "status": "solver_supported",
        "signals": [
            "Ruby attachment requires doublehelix",
            "Body consists of A/T/G/C bases, hyphens, and missing spaces",
            "Some DNA-art rows are partially or fully blank after corruption",
        ],
        "recommended_steps": [
            "Recover each row against the mame/doublehelix 18-row format cycle",
            "Enumerate only the small set of fully ambiguous base pairs",
            "Decode pair bits with Ruby pack('b*') little-endian byte order and rank leetspeak flag candidates",
        ],
        "solver_paths": ["MiscSolver.doublehelix_decay"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "misc-recursive-regex-golf",
        "title": "Recursive regex golf verifier",
        "category": "misc",
        "status": "manual_replay_script",
        "signals": [
            "Challenge service asks for short regexes across several levels",
            "Verifier uses the Python regex module with recursive constructs enabled",
            "Tasks include unary arithmetic, balanced brackets, palindromes, or multiplication",
        ],
        "recommended_steps": [
            "Derive the shortest intended recursive regex for each level",
            "Replay against the local challenge service instead of reading flag.txt",
            "Preserve pattern count, length bounds, and transcript flag evidence",
        ],
        "solver_paths": ["scripts/solve_golf_hard.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "misc-python-eval-blacklist-bypass",
        "title": "Python eval blacklist bypass",
        "category": "misc",
        "status": "manual_replay_script",
        "signals": [
            "Source calls eval(user_input + '()') or appends a call suffix after user input",
            "Blacklist blocks imports, shell words, digits, or braces but leaves print/open/read-style primitives",
            "Single quote and # are still accepted by the input filter",
        ],
        "recommended_steps": [
            "Parse the blacklist from source and prove the payload does not contain blocked substrings",
            "Use # to comment out the challenge-appended call suffix when the input is evaluated",
            "Replay locally with a challenge-scoped flag.txt fixture when the original remote flag file was not shipped",
        ],
        "solver_paths": ["scripts/solve_unbreakable.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "misc-vivado-dcp-edif-lut",
        "title": "Vivado DCP EDIF LUT netlist",
        "category": "misc",
        "status": "manual_replay_script",
        "signals": [
            "Attachment is a Vivado project archive with .dcp checkpoints but missing original HDL source",
            "DCP file is a ZIP container with main.edf, main_stub.v, and implementation metadata",
            "Small LUT5/LUT6 netlist drives switches, LEDs, anodes, or seven-segment outputs",
        ],
        "recommended_steps": [
            "Extract the DCP as a ZIP archive and read main.edf",
            "Parse LUT INIT values and net joins, then simulate the small combinational netlist",
            "Map active-low seven-segment and anode outputs back to the assignment table before forming the flag",
        ],
        "solver_paths": ["scripts/solve_ee2026.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "misc-i2c-eeprom-schematic-dump",
        "title": "I2C EEPROM schematic dump",
        "category": "misc",
        "status": "manual_replay_script",
        "signals": [
            "Schematic exposes an M24C0x EEPROM component",
            "SDA and SCL nets are visible near connector GPIO labels",
            "A local EEPROM dump or hardware read transcript is available",
        ],
        "recommended_steps": [
            "Extract schematic text or render evidence for the EEPROM and I2C nets",
            "Read the EEPROM dump as bytes and scan printable text for the flag",
            "Preserve component name, bus signals, and dump-derived flag evidence",
        ],
        "solver_paths": ["scripts/solve_i_see.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "misc-sparse-adversarial-pixels",
        "title": "Sparse adversarial pixel replay",
        "category": "misc",
        "status": "manual_replay_script",
        "signals": [
            "Challenge ships model.pt, server.py, and an image with a small pixel-change budget",
            "Server asks for x,y,r,g,b entries and verifies a local classifier score",
            "PyTorch train/eval mode changes the classifier score and must match server.py",
            "Train-mode BatchNorm makes batched candidate scoring differ from the single-image service path",
        ],
        "recommended_steps": [
            "Run --score-only locally in Docker and preserve the original single-image model score",
            "Use --search-unstable with explicit seed or --search-seeds sweeps, step/trial bounds, --search-output, and --payload-output for reproducible local payload search",
            "Generate or supply a bounded adversarial pixel payload with at most the allowed count",
            "Submit the payload to the provided local service and accept only service-returned flags",
        ],
        "solver_paths": ["scripts/solve_attack_of_the_worm.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "pwn-ret2win-escaped-bytes",
        "title": "ret2win escaped-byte input",
        "category": "pwn",
        "status": "manual_replay_script",
        "signals": [
            "Non-PIE ELF exposes a win-like symbol",
            "Stack buffer return address is visible or documented at a fixed offset",
            "Input parser accepts escaped hex bytes such as \\41 for raw byte insertion",
        ],
        "recommended_steps": [
            "Locate the win symbol with objdump or nm",
            "Build padding plus little-endian win address using the challenge's escaped-byte syntax",
            "Replay inside a local Linux container and reject placeholder training flags",
        ],
        "solver_paths": ["scripts/solve_bof_school.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "pwn-int16-hp-overflow",
        "title": "signed short HP overflow",
        "category": "pwn",
        "status": "manual_replay_script",
        "signals": [
            "Game-style C source stores health or score in short int",
            "A safe-looking action repeatedly increases the signed 16-bit value",
            "Win condition checks whether the wrapped value is less than or equal to zero",
        ],
        "recommended_steps": [
            "Model the signed 16-bit wraparound instead of brute-forcing the interaction",
            "Replay the minimal action stream against the local challenge binary",
            "Reject test flags and preserve action count plus transcript evidence",
        ],
        "solver_paths": ["scripts/solve_epic_boss_fight.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "pwn-heap-off-by-one-overlap",
        "title": "heap off-by-one overlap",
        "category": "pwn",
        "status": "manual_replay_script",
        "signals": [
            "C source writes one byte past a heap chunk into the next chunk size field",
            "A later free and malloc can return an overlapping chunk",
            "Flag bytes are already loaded into a neighboring heap allocation",
        ],
        "recommended_steps": [
            "Choose the corrupted size byte that keeps allocator checks valid",
            "Request the allocation size that overlaps the flag-bearing chunk",
            "Preserve chunk addresses, overlap assertion output, and the printed flag",
        ],
        "solver_paths": ["scripts/solve_baby_heap.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "pwn-suffix-retaddr-alignment",
        "title": "suffix bytes retaddr alignment",
        "category": "pwn",
        "status": "manual_replay_script",
        "signals": [
            "Non-PIE ELF has an unusual win address that decodes to printable bytes",
            "A bounded input is followed by an unsafe append of a fixed suffix",
            "The fixed suffix contains the little-endian target address bytes",
        ],
        "recommended_steps": [
            "Calculate the stack offset from the destination buffer to saved RIP",
            "Find the target address byte sequence inside the fixed suffix",
            "Choose the input length that aligns those suffix bytes over the return address and replay locally",
        ],
        "solver_paths": ["scripts/solve_insanity_check.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "pwn-uaf-uninitialized-list-next",
        "title": "UAF uninitialized list next",
        "category": "pwn",
        "status": "manual_replay_script",
        "signals": [
            "Freed user/account chunks are reallocated by a later signup path",
            "A linked-list entry leaves next or prev uninitialized after malloc",
            "Old user-controlled bytes can become a pointer to a fake list node or fake user",
        ],
        "recommended_steps": [
            "Preserve allocation and free order for user and list-entry chunks",
            "Find a stable zero-filled or controlled pointer target in the non-PIE binary",
            "Replay the menu interaction byte-for-byte against a local Linux container",
        ],
        "solver_paths": ["scripts/solve_sign_in.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "pwn-aarch64-pac-signing-oracle",
        "title": "AArch64 PAC signing oracle",
        "category": "pwn",
        "status": "manual_replay_script",
        "signals": [
            "AArch64 binary prints PAC-signed function pointers before indirect calls",
            "Challenge exposes arbitrary 64-bit read and write helpers",
            "A helper such as help() signs writable table entries before printing them",
        ],
        "recommended_steps": [
            "Use the signed helper leak to derive PIE and call an imported function to resolve its GOT entry",
            "Read libc environ to locate the active stack frame without blind unmapped reads",
            "Overwrite a builtin table entry with a libc gadget, let the challenge sign it, then execute a bounded local shell command",
        ],
        "solver_paths": ["scripts/solve_pac_shell.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "pwn-glibc-tcache-malloc-hook",
        "title": "glibc tcache malloc hook",
        "category": "pwn",
        "status": "manual_replay_script",
        "signals": [
            "Menu exposes one global heap pointer with alloc, free, edit, and print-after-free behavior",
            "Freed chunk contents can leak heap-safe-linking mask bytes or a libc arena pointer",
            "The shipped glibc still has reachable __malloc_hook and system symbols",
        ],
        "recommended_steps": [
            "Leak the heap mask from a freed tcache chunk and leak libc from a large freed chunk",
            "Poison the tcache fd with heap >> 12 xor __malloc_hook",
            "Overwrite __malloc_hook with system, then malloc a /bin/sh string under local Docker replay",
        ],
        "solver_paths": ["scripts/solve_chisel.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "pwn-ret2vdso-vm-artifact-check",
        "title": "ret2vdso VM artifact check",
        "category": "pwn",
        "status": "backlog_gap",
        "signals": [
            "Challenge README references QEMU, vmlinuz-linux, initramfs.cpio.gz, run.sh, or a tiny setuid /target binary",
            "Exploit uses a fixed VDSO_BASE_ADDR plus syscall-oriented gadgets",
            "Local cache has writeup or exploit text but not the bootable VM handout artifacts",
        ],
        "recommended_steps": [
            "Treat the case as blocked until the original kernel, rootfs, run script, and target binary are present",
            "Parse ret2vdso constants and payload shape from the exploit for specialist review",
            "Accept a flag only after replaying the payload against the local authorized VM and capturing /root/flag.txt",
        ],
        "solver_paths": ["scripts/solve_maze_of_mist_static.py"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md", "docs/solve-scripts.md"],
    },
    {
        "id": "reverse-elf-argv-repeating-xor",
        "title": "ELF argv repeating XOR validation",
        "category": "reverse",
        "status": "solver_supported",
        "signals": [
            "ELF imports or strings mention strlen, strcmp, ptrace, right/wrong style status text",
            "main initializes a short stack byte string with mov dword/word/byte [rbp-offset], immediate",
            "strcmp compares a transformed argv buffer against a printable .rodata string",
        ],
        "recommended_steps": [
            "Dump main with objdump -d -M intel and locate the argv XOR loop",
            "Recover little-endian stack key bytes and the .rodata ciphertext address used before strcmp",
            "Decode plaintext[i] = ciphertext[i] ^ key[i % len(key)] and verify the recovered submission input",
        ],
        "solver_paths": ["ReverseSolver.elf_argv_repeating_xor"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "reverse-jmp-popcount-table",
        "title": "jmp-table popcount ordering",
        "category": "reverse",
        "status": "solver_supported",
        "signals": [
            "Local ELF has dense fixed-size dispatch blocks",
            "Blocks contain large and/movabs immediate masks",
            "Character order appears encoded by mask dependencies",
        ],
        "recommended_steps": [
            "Disassemble the block window from bytes with Capstone",
            "Extract per-character dependency masks",
            "Order characters by popcount and wrap with the platform prefix",
        ],
        "solver_paths": ["ReverseSolver.jmp_table_popcount"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "reverse-compiled-byte-equality-chain",
        "title": "Compiled byte equality chain",
        "category": "reverse",
        "status": "solver_supported",
        "signals": [
            "Local ELF exposes helper names such as read_byte or challenge entry symbols",
            "Validation compares input bytes against immediate constants through tagged integer values",
            "Tool-wrapper disassembly may truncate before the useful validation entry point",
        ],
        "recommended_steps": [
            "Scan disassembly around read_byte calls for nearby mov eax immediates",
            "Fallback to binary-byte scanning when objdump output is truncated",
            "Decode tagged immediates such as input_byte * 2 and verify flag-format candidates",
        ],
        "solver_paths": ["ReverseSolver.compiled_byte_equality_chain"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "reverse-pe-stack-xor-key-check",
        "title": "PE stack XOR key check",
        "category": "reverse",
        "status": "solver_supported",
        "signals": [
            "PE32/i386 console binary prompts for a key and prints right/error status strings",
            "Validation function initializes many stack bytes before comparing user input",
            "A short local decoder generates an XOR key from a small immediate seed",
        ],
        "recommended_steps": [
            "Scan x86 stack-byte initializers near key-check functions",
            "Recover the length and seed from push immediates before the decoder call",
            "Regenerate the XOR stream, decrypt the stack byte array, and verify flag-format candidates",
        ],
        "solver_paths": ["ReverseSolver.pe_stack_xor_key_check"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "reverse-mlvm-pixel-art",
        "title": "MLVM pixel-art validation",
        "category": "reverse",
        "status": "solver_supported",
        "signals": [
            "Attachment starts with MLVM and contains function names plus ANSI paint strings",
            "Bytecode validates many 4-byte canvas chunks with movc triplets and a helper call",
            "Success text asks to wrap the name of the recovered image in a CTF flag wrapper",
        ],
        "recommended_steps": [
            "Parse MLVM function names and scan only helper-call validation triplets",
            "Invert each 4-byte color chunk into a low-resolution canvas",
            "Render the canvas as evidence and classify conservative pixel-art templates",
        ],
        "solver_paths": ["ReverseSolver.mlvm_pixel_art"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "reverse-python-vm-perfect-sha1",
        "title": "Python VM perfect-number SHA1 flag",
        "category": "reverse",
        "status": "solver_supported",
        "signals": [
            "Python VM source contains PRINTFLAG, flag_enc, and hashlib.sha1",
            "Program compares a generated value with modulus/remainder predicates",
        ],
        "recommended_steps": [
            "Parse encrypted flag bytes and MOV modulus/remainder candidates",
            "Enumerate known Mersenne-prime perfect numbers",
            "Repeat the SHA1 digest to the encrypted flag length and verify decoded candidates",
        ],
        "solver_paths": ["ReverseSolver.python_vm_perfect_number_sha1"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
    {
        "id": "reverse-python-grid-constraints",
        "title": "Python 8x8 grid byte constraints",
        "category": "reverse",
        "status": "solver_supported",
        "signals": [
            "Python or Tkinter challenge uses grid = [0]*64",
            "Verifier accumulates many boolean constraints before returning chr(bN) bytes",
        ],
        "recommended_steps": [
            "Model grid bits as bounded 0/1 variables",
            "Add row, column, diagonal, hamming, xor, and popcount constraints",
            "Constrain returned bytes to common CTF flag-body characters when models are non-unique",
        ],
        "solver_paths": ["ReverseSolver.python_grid_constraints"],
        "docs": ["docs/ctf-casebook.md", "docs/ctf-playbook.md"],
    },
)


def recommended_analysis_hints(category: str | None = None) -> list[dict[str, Any]]:
    hints = [dict(hint) for hint in ANALYSIS_HINTS]
    if category:
        hints = [hint for hint in hints if hint["category"] == category]
    return sorted(hints, key=lambda hint: (hint["category"], hint["id"]))
