from __future__ import annotations

from typing import Any


PROJECT_CATALOG: tuple[dict[str, Any], ...] = (
    {
        "name": "CTFd",
        "categories": ["infra"],
        "url": "https://github.com/CTFd/CTFd",
        "purpose": "CTF platform and scoreboard for Jeopardy-style events.",
        "why": "Widely used event platform; useful for future scoreboard ingestion and challenge sync.",
        "integration": "future_connector",
        "install_hint": "Run as a separate service; integrate through CTFd API rather than local shell wrappers.",
    },
    {
        "name": "pwntools",
        "categories": ["pwn"],
        "url": "https://github.com/Gallopsled/pwntools",
        "purpose": "Python exploit-development and CTF automation framework.",
        "why": "Standard workflow for process/socket interaction, packing, ELF, ROP, shellcraft, and exploit scripts.",
        "integration": "solver_workspace",
        "install_hint": "pip install pwntools",
    },
    {
        "name": "pwndbg",
        "categories": ["pwn", "reverse"],
        "url": "https://github.com/pwndbg/pwndbg",
        "purpose": "GDB plugin focused on exploit development and reverse engineering.",
        "why": "Improves heap/stack/register/context inspection for pwn debugging.",
        "integration": "docker_candidate",
        "install_hint": "Install inside the pwn/reverse tool container with GDB.",
    },
    {
        "name": "GEF",
        "categories": ["pwn", "reverse"],
        "url": "https://github.com/hugsy/gef",
        "purpose": "GDB enhancement plugin for exploit development.",
        "why": "Lightweight alternative or complement to pwndbg for binary debugging.",
        "integration": "docker_candidate",
        "install_hint": "Install inside the pwn/reverse tool container with GDB.",
    },
    {
        "name": "ROPgadget",
        "categories": ["pwn", "reverse"],
        "url": "https://github.com/JonathanSalwan/ROPgadget",
        "purpose": "Search ROP/JOP gadgets in binaries.",
        "why": "Directly supports exploit-chain construction after checksec and crash triage.",
        "integration": "wrapper_candidate",
        "install_hint": "pip install ROPGadget",
    },
    {
        "name": "Ropper",
        "categories": ["pwn", "reverse"],
        "url": "https://github.com/sashs/Ropper",
        "purpose": "Find gadgets and build ROP chains.",
        "why": "Useful second opinion for gadget discovery when ROPgadget misses a pattern.",
        "integration": "wrapper_candidate",
        "install_hint": "pip install ropper",
    },
    {
        "name": "Ghidra",
        "categories": ["reverse", "pwn"],
        "url": "https://github.com/NationalSecurityAgency/ghidra",
        "purpose": "Software reverse engineering suite.",
        "why": "Primary open-source decompiler/disassembler option for reverse and pwn triage.",
        "integration": "external_gui_or_mcp",
        "install_hint": "Install separately; call through export scripts or MCP-style read-only adapters.",
    },
    {
        "name": "radare2",
        "categories": ["reverse", "pwn"],
        "url": "https://github.com/radareorg/radare2",
        "purpose": "Command-line reverse engineering framework.",
        "why": "Scriptable binary analysis fits ForgeFlag wrapper execution better than GUI-only workflows.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install radare2",
    },
    {
        "name": "Rizin",
        "categories": ["reverse", "pwn"],
        "url": "https://github.com/rizinorg/rizin",
        "purpose": "Fork of radare2 focused on maintainable reverse engineering tooling.",
        "why": "Good candidate for scripted reverse workflows and future typed wrappers.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install rizin",
    },
    {
        "name": "angr",
        "categories": ["reverse", "pwn"],
        "url": "https://github.com/angr/angr",
        "purpose": "Binary analysis framework for symbolic execution and program analysis.",
        "why": "Good fit for crackme path solving, symbolic constraints, and reachability analysis.",
        "integration": "solver_workspace",
        "install_hint": "pip install angr",
    },
    {
        "name": "CyberChef",
        "categories": ["crypto", "misc", "forensics"],
        "url": "https://github.com/gchq/CyberChef",
        "purpose": "Encoding, decoding, compression, crypto, and data transformation workbench.",
        "why": "High-value reference for recipe-style transform chains and misc/crypto automation ideas.",
        "integration": "recipe_reference",
        "install_hint": "Use hosted UI or run locally; model recipes as future ForgeFlag transform steps.",
    },
    {
        "name": "RsaCtfTool",
        "categories": ["crypto"],
        "url": "https://github.com/RsaCtfTool/RsaCtfTool",
        "purpose": "RSA weak-key and CTF attack toolkit.",
        "why": "Directly maps to common RSA CTF failure modes and key-parameter triage.",
        "integration": "wrapper_candidate",
        "install_hint": "pip install git+https://github.com/RsaCtfTool/RsaCtfTool.git",
    },
    {
        "name": "Z3",
        "categories": ["crypto", "reverse", "misc"],
        "url": "https://github.com/Z3Prover/z3",
        "purpose": "SMT solver for constraints.",
        "why": "Core dependency for symbolic crypto, crackme constraints, and puzzle solving.",
        "integration": "library_dependency",
        "install_hint": "pip install z3-solver",
    },
    {
        "name": "SageMath",
        "categories": ["crypto"],
        "url": "https://github.com/sagemath/sage",
        "purpose": "Mathematics system for number theory and algebra.",
        "why": "Useful for lattice, finite-field, elliptic-curve, and RSA math-heavy challenges.",
        "integration": "docker_candidate",
        "install_hint": "Use Docker or system package; avoid forcing it into the base Python venv.",
    },
    {
        "name": "Binwalk",
        "categories": ["forensics", "misc"],
        "url": "https://github.com/ReFirmLabs/binwalk",
        "purpose": "Firmware and embedded-file signature scanner.",
        "why": "Already in ForgeFlag; keep as the first broad binary/container triage step.",
        "integration": "existing_wrapper",
        "install_hint": "brew install binwalk",
    },
    {
        "name": "ExifTool",
        "categories": ["forensics", "misc"],
        "url": "https://github.com/exiftool/exiftool",
        "purpose": "Metadata extraction for images and documents.",
        "why": "Already in ForgeFlag; useful for image/document metadata pivots.",
        "integration": "existing_wrapper",
        "install_hint": "brew install exiftool",
    },
    {
        "name": "Volatility 3",
        "categories": ["forensics"],
        "url": "https://github.com/volatilityfoundation/volatility3",
        "purpose": "Memory image analysis framework.",
        "why": "Needed for memory forensics milestone; should live in a heavier tool container.",
        "integration": "docker_candidate",
        "install_hint": "pip install volatility3",
    },
    {
        "name": "Didier Stevens Suite",
        "categories": ["forensics", "misc"],
        "url": "https://github.com/DidierStevens/DidierStevensSuite",
        "purpose": "Document, PDF, OLE, and malware-analysis helper scripts.",
        "why": "Strong coverage for Office/PDF CTF artifacts beyond generic strings/binwalk.",
        "integration": "wrapper_candidate",
        "install_hint": "Install selected scripts in a forensics container.",
    },
    {
        "name": "Wireshark",
        "categories": ["traffic", "forensics"],
        "url": "https://gitlab.com/wireshark/wireshark",
        "purpose": "Packet analysis suite; provides tshark CLI.",
        "why": "ForgeFlag already uses tshark; future traffic work should deepen HTTP/DNS/TCP stream extraction.",
        "integration": "existing_wrapper",
        "install_hint": "brew install wireshark or tshark",
    },
    {
        "name": "Scapy",
        "categories": ["traffic", "misc"],
        "url": "https://github.com/secdev/scapy",
        "purpose": "Python packet manipulation and parsing library.",
        "why": "Good for custom protocol parsing when tshark fields are insufficient.",
        "integration": "library_dependency",
        "install_hint": "pip install scapy",
    },
    {
        "name": "sqlmap",
        "categories": ["web"],
        "url": "https://github.com/sqlmapproject/sqlmap",
        "purpose": "SQL injection detection and exploitation tool.",
        "why": "Useful only behind strict scope controls; should not become default active probing.",
        "integration": "scoped_active_wrapper_candidate",
        "install_hint": "Install in web tool container; require allowed host and active probe.",
    },
    {
        "name": "ffuf",
        "categories": ["web"],
        "url": "https://github.com/ffuf/ffuf",
        "purpose": "Fast web fuzzer for paths, parameters, and virtual hosts.",
        "why": "Good next step for scoped route discovery with request budgets.",
        "integration": "scoped_active_wrapper_candidate",
        "install_hint": "brew install ffuf",
    },
    {
        "name": "nuclei",
        "categories": ["web", "infra"],
        "url": "https://github.com/projectdiscovery/nuclei",
        "purpose": "Template-based vulnerability scanner.",
        "why": "Useful for authorized CTF infrastructure checks, but must be scope-gated.",
        "integration": "scoped_active_wrapper_candidate",
        "install_hint": "brew install nuclei",
    },
    {
        "name": "hashcat",
        "categories": ["crypto", "misc"],
        "url": "https://github.com/hashcat/hashcat",
        "purpose": "Password/hash recovery.",
        "why": "Useful for hash cracking tasks; should be optional because GPU/driver setup varies.",
        "integration": "docker_or_host_tool",
        "install_hint": "brew install hashcat or use host GPU environment.",
    },
    {
        "name": "John the Ripper",
        "categories": ["crypto", "misc"],
        "url": "https://github.com/openwall/john",
        "purpose": "Password/hash recovery suite.",
        "why": "Complements hashcat and works well on CPU-only setups.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install john",
    },
    {
        "name": "Burp Suite Community",
        "categories": ["web"],
        "url": "https://portswigger.net/burp/communitydownload",
        "purpose": "Intercepting proxy for manual web challenge analysis.",
        "why": "Best manual companion for request mutation, cookies, auth flows, and hidden API exploration.",
        "integration": "external_gui",
        "install_hint": "Install separately; use for manual request capture rather than headless wrappers.",
    },
    {
        "name": "curl",
        "categories": ["web", "infra"],
        "url": "https://curl.se/",
        "purpose": "HTTP client for reproducible request/response captures.",
        "why": "Smallest reliable reproduction primitive for web solver paths and headers.",
        "integration": "wrapper_candidate",
        "install_hint": "Usually preinstalled; brew install curl",
    },
    {
        "name": "HTTPie",
        "categories": ["web"],
        "url": "https://github.com/httpie/cli",
        "purpose": "Human-friendly HTTP client.",
        "why": "Useful for readable API testing when curl commands become noisy.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install httpie or pip install httpie",
    },
    {
        "name": "httpx",
        "categories": ["web", "infra"],
        "url": "https://github.com/projectdiscovery/httpx",
        "purpose": "Fast HTTP probing and technology fingerprinting.",
        "why": "Good for scoped target liveness, title, status, and tech summaries.",
        "integration": "scoped_active_wrapper_candidate",
        "install_hint": "brew install httpx or go install github.com/projectdiscovery/httpx/cmd/httpx@latest",
    },
    {
        "name": "katana",
        "categories": ["web"],
        "url": "https://github.com/projectdiscovery/katana",
        "purpose": "Web crawler for endpoint discovery.",
        "why": "Useful after first response parsing when scoped route graph expansion is allowed.",
        "integration": "scoped_active_wrapper_candidate",
        "install_hint": "go install github.com/projectdiscovery/katana/cmd/katana@latest",
    },
    {
        "name": "feroxbuster",
        "categories": ["web"],
        "url": "https://github.com/epi052/feroxbuster",
        "purpose": "Recursive content discovery.",
        "why": "Alternative to ffuf for directory brute force with scope and rate limits.",
        "integration": "scoped_active_wrapper_candidate",
        "install_hint": "brew install feroxbuster",
    },
    {
        "name": "gobuster",
        "categories": ["web"],
        "url": "https://github.com/OJ/gobuster",
        "purpose": "Directory, DNS, and vhost brute forcing.",
        "why": "Common CTF fallback for scoped route and vhost discovery.",
        "integration": "scoped_active_wrapper_candidate",
        "install_hint": "brew install gobuster",
    },
    {
        "name": "dirsearch",
        "categories": ["web"],
        "url": "https://github.com/maurosoria/dirsearch",
        "purpose": "Web path discovery.",
        "why": "Widely used Python content discovery tool for CTF web challenges.",
        "integration": "scoped_active_wrapper_candidate",
        "install_hint": "pipx install dirsearch",
    },
    {
        "name": "Arjun",
        "categories": ["web"],
        "url": "https://github.com/s0md3v/Arjun",
        "purpose": "HTTP parameter discovery.",
        "why": "Useful for hidden parameter CTF tasks after route discovery.",
        "integration": "scoped_active_wrapper_candidate",
        "install_hint": "pipx install arjun",
    },
    {
        "name": "jwt_tool",
        "categories": ["web", "crypto"],
        "url": "https://github.com/ticarpi/jwt_tool",
        "purpose": "JWT inspection, testing, and exploitation helper.",
        "why": "Maps directly to auth/session CTF challenges with JWT weaknesses.",
        "integration": "wrapper_candidate",
        "install_hint": "pipx install jwt-tool",
    },
    {
        "name": "tplmap",
        "categories": ["web"],
        "url": "https://github.com/epinna/tplmap",
        "purpose": "Server-side template injection detection and exploitation helper.",
        "why": "Useful as a manual or scoped follow-up when template clues are present.",
        "integration": "scoped_active_wrapper_candidate",
        "install_hint": "Install in web tool container; run only with explicit scope.",
    },
    {
        "name": "commix",
        "categories": ["web"],
        "url": "https://github.com/commixproject/commix",
        "purpose": "Command injection testing helper.",
        "why": "Useful only after command-injection evidence appears and scope allows active testing.",
        "integration": "scoped_active_wrapper_candidate",
        "install_hint": "brew install commix or use a web tool container.",
    },
    {
        "name": "Ciphey",
        "categories": ["crypto", "misc"],
        "url": "https://github.com/Ciphey/Ciphey",
        "purpose": "Automated decoding and classical cipher identification.",
        "why": "Good reference for transform search and quick CTF layer peeling.",
        "integration": "wrapper_candidate",
        "install_hint": "pipx install ciphey",
    },
    {
        "name": "python-codext",
        "categories": ["crypto", "misc"],
        "url": "https://github.com/dhondta/python-codext",
        "purpose": "Large collection of codecs and encoding transforms.",
        "why": "Useful model for extending ForgeFlag transform candidates beyond built-ins.",
        "integration": "library_dependency",
        "install_hint": "pip install codext",
    },
    {
        "name": "PyCryptodome",
        "categories": ["crypto"],
        "url": "https://github.com/Legrandin/pycryptodome",
        "purpose": "Python cryptographic primitives for solve scripts.",
        "why": "Standard dependency for AES, DES, RSA, and hash challenge scripting.",
        "integration": "library_dependency",
        "install_hint": "pip install pycryptodome",
    },
    {
        "name": "gmpy2",
        "categories": ["crypto"],
        "url": "https://github.com/aleaxit/gmpy",
        "purpose": "Fast big integer arithmetic.",
        "why": "Useful for RSA, modular roots, inverses, and number theory helpers.",
        "integration": "library_dependency",
        "install_hint": "pip install gmpy2",
    },
    {
        "name": "SymPy",
        "categories": ["crypto", "misc"],
        "url": "https://github.com/sympy/sympy",
        "purpose": "Symbolic mathematics and number theory helpers.",
        "why": "Lightweight option for modular arithmetic and puzzle constraints before SageMath.",
        "integration": "library_dependency",
        "install_hint": "pip install sympy",
    },
    {
        "name": "fpylll",
        "categories": ["crypto"],
        "url": "https://github.com/fplll/fpylll",
        "purpose": "Python bindings for lattice reduction.",
        "why": "Useful for LLL/Coppersmith-style crypto challenges.",
        "integration": "docker_candidate",
        "install_hint": "Install in SageMath/crypto container.",
    },
    {
        "name": "YAFU",
        "categories": ["crypto"],
        "url": "https://github.com/bbuhrow/yafu",
        "purpose": "Integer factorization utility.",
        "why": "Useful for RSA modulus factorization attempts and factorization triage.",
        "integration": "docker_candidate",
        "install_hint": "Install in crypto tool container.",
    },
    {
        "name": "xortool",
        "categories": ["crypto", "misc"],
        "url": "https://github.com/hellman/xortool",
        "purpose": "XOR cipher key-length and key recovery helper.",
        "why": "Common CTF tool for repeated-key XOR and known-plaintext attacks.",
        "integration": "wrapper_candidate",
        "install_hint": "pipx install xortool",
    },
    {
        "name": "hashid",
        "categories": ["crypto", "misc"],
        "url": "https://github.com/psypanda/hashID",
        "purpose": "Hash type identification.",
        "why": "Complements ForgeFlag hash fingerprinting with an external opinion.",
        "integration": "wrapper_candidate",
        "install_hint": "pipx install hashid",
    },
    {
        "name": "The Sleuth Kit",
        "categories": ["forensics"],
        "url": "https://github.com/sleuthkit/sleuthkit",
        "purpose": "Disk image and filesystem forensic analysis.",
        "why": "Needed for disk image triage, deleted files, and filesystem timelines.",
        "integration": "docker_candidate",
        "install_hint": "brew install sleuthkit or use forensics container.",
    },
    {
        "name": "Autopsy",
        "categories": ["forensics"],
        "url": "https://github.com/sleuthkit/autopsy",
        "purpose": "GUI forensic browser built around Sleuth Kit workflows.",
        "why": "Manual disk-forensics companion for complex images.",
        "integration": "external_gui",
        "install_hint": "Install separately; keep ForgeFlag integration through exported evidence.",
    },
    {
        "name": "TestDisk/PhotoRec",
        "categories": ["forensics"],
        "url": "https://www.cgsecurity.org/wiki/TestDisk",
        "purpose": "File recovery and carving utility.",
        "why": "Useful for deleted-file and media-recovery CTF tasks.",
        "integration": "docker_candidate",
        "install_hint": "brew install testdisk",
    },
    {
        "name": "foremost",
        "categories": ["forensics", "misc"],
        "url": "https://github.com/korczis/foremost",
        "purpose": "File carving by headers and footers.",
        "why": "Common follow-up after binwalk or strings indicate embedded payloads.",
        "integration": "docker_candidate",
        "install_hint": "Install in forensics container.",
    },
    {
        "name": "bulk_extractor",
        "categories": ["forensics"],
        "url": "https://github.com/simsong/bulk_extractor",
        "purpose": "Extract emails, URLs, domains, and other features from disk images.",
        "why": "Useful for broad evidence collection from forensic images.",
        "integration": "docker_candidate",
        "install_hint": "Install in forensics container.",
    },
    {
        "name": "pngcheck",
        "categories": ["forensics", "misc"],
        "url": "http://www.libpng.org/pub/png/apps/pngcheck.html",
        "purpose": "PNG structure and chunk validation.",
        "why": "Useful for IHDR/chunk/CRC puzzle triage.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install pngcheck",
    },
    {
        "name": "zsteg",
        "categories": ["forensics", "misc"],
        "url": "https://github.com/zed-0xff/zsteg",
        "purpose": "PNG/BMP LSB steganography detector.",
        "why": "Common CTF tool for image bit-plane and channel hints.",
        "integration": "wrapper_candidate",
        "install_hint": "gem install zsteg",
    },
    {
        "name": "steghide",
        "categories": ["forensics", "misc"],
        "url": "https://github.com/StefanoDeVuono/steghide",
        "purpose": "Hide/extract data in JPEG, BMP, WAV, and AU files.",
        "why": "Common CTF stego tool when a passphrase is known or guessed.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install steghide",
    },
    {
        "name": "stegseek",
        "categories": ["forensics", "misc"],
        "url": "https://github.com/RickdeJager/stegseek",
        "purpose": "Fast steghide passphrase recovery.",
        "why": "Useful for steghide challenges with explicit wordlists; should be bounded.",
        "integration": "manual_or_bounded_wrapper_candidate",
        "install_hint": "brew install stegseek or use forensics container.",
    },
    {
        "name": "binwalk-ng",
        "categories": ["forensics", "misc"],
        "url": "https://github.com/ReFirmLabs/binwalk",
        "purpose": "Modern binwalk release line for embedded file analysis.",
        "why": "Track compatibility for future carving/extraction improvements.",
        "integration": "reference_only",
        "install_hint": "Prefer packaged binwalk in the ForgeFlag tool container.",
    },
    {
        "name": "oletools",
        "categories": ["forensics"],
        "url": "https://github.com/decalage2/oletools",
        "purpose": "Microsoft Office/OLE macro and document analysis.",
        "why": "Useful for Office macro and malicious document CTF forensics.",
        "integration": "wrapper_candidate",
        "install_hint": "pipx install oletools",
    },
    {
        "name": "qpdf",
        "categories": ["forensics", "misc"],
        "url": "https://github.com/qpdf/qpdf",
        "purpose": "PDF structure inspection and transformation.",
        "why": "Useful for PDF object, stream, and repair challenges.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install qpdf",
    },
    {
        "name": "pdf-parser.py",
        "categories": ["forensics", "misc"],
        "url": "https://github.com/DidierStevens/DidierStevensSuite",
        "purpose": "PDF object and stream inspection.",
        "why": "High-value single script from Didier Stevens Suite for PDF CTFs.",
        "integration": "wrapper_candidate",
        "install_hint": "Install selected Didier Stevens scripts in forensics container.",
    },
    {
        "name": "Zeek",
        "categories": ["traffic", "forensics"],
        "url": "https://github.com/zeek/zeek",
        "purpose": "Network security monitor that turns PCAPs into structured logs.",
        "why": "Excellent next step for HTTP/DNS/SMTP/SSL conversation summaries beyond tshark fields.",
        "integration": "docker_candidate",
        "install_hint": "brew install zeek or use traffic container.",
    },
    {
        "name": "tcpdump",
        "categories": ["traffic", "infra"],
        "url": "https://www.tcpdump.org/",
        "purpose": "Packet capture and quick packet filtering.",
        "why": "Useful for quick capture validation and BPF-style filtering.",
        "integration": "wrapper_candidate",
        "install_hint": "Usually preinstalled; brew install tcpdump",
    },
    {
        "name": "ngrep",
        "categories": ["traffic"],
        "url": "https://github.com/jpr5/ngrep",
        "purpose": "Grep-like packet payload inspection.",
        "why": "Useful lightweight fallback for printable payload hunts.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install ngrep",
    },
    {
        "name": "NetworkMiner",
        "categories": ["traffic", "forensics"],
        "url": "https://www.netresec.com/?page=NetworkMiner",
        "purpose": "Network forensic file/session extraction GUI.",
        "why": "Manual companion for PCAP object extraction and host summaries.",
        "integration": "external_gui",
        "install_hint": "Install separately; use exported evidence in ForgeFlag.",
    },
    {
        "name": "GDB",
        "categories": ["pwn", "reverse"],
        "url": "https://sourceware.org/gdb/",
        "purpose": "Debugger for native binaries.",
        "why": "Required for crash reproduction, offsets, breakpoints, and exploit debugging.",
        "integration": "docker_candidate",
        "install_hint": "Install in pwn/reverse container with pwndbg or GEF.",
    },
    {
        "name": "pwninit",
        "categories": ["pwn"],
        "url": "https://github.com/io12/pwninit",
        "purpose": "Patch challenge binaries with matching libc/ld and create templates.",
        "why": "Speeds up ret2libc and remote libc matching workflows.",
        "integration": "solver_workspace",
        "install_hint": "Install in pwn container.",
    },
    {
        "name": "patchelf",
        "categories": ["pwn", "reverse"],
        "url": "https://github.com/NixOS/patchelf",
        "purpose": "Modify ELF interpreter and rpath.",
        "why": "Useful for reproducing remote libc/ld environments locally.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install patchelf",
    },
    {
        "name": "one_gadget",
        "categories": ["pwn"],
        "url": "https://github.com/david942j/one_gadget",
        "purpose": "Find one-shot RCE gadgets in libc.",
        "why": "Common ret2libc follow-up once libc base is known.",
        "integration": "wrapper_candidate",
        "install_hint": "gem install one_gadget",
    },
    {
        "name": "libc-database",
        "categories": ["pwn"],
        "url": "https://github.com/niklasb/libc-database",
        "purpose": "Identify libc versions from leaked symbols.",
        "why": "Useful when a pwn challenge leaks libc addresses.",
        "integration": "solver_workspace",
        "install_hint": "Clone into pwn workspace or container.",
    },
    {
        "name": "seccomp-tools",
        "categories": ["pwn"],
        "url": "https://github.com/david942j/seccomp-tools",
        "purpose": "Inspect and dump seccomp filters.",
        "why": "Useful for shellcode/sandbox pwn challenges.",
        "integration": "wrapper_candidate",
        "install_hint": "gem install seccomp-tools",
    },
    {
        "name": "QEMU user",
        "categories": ["pwn", "reverse"],
        "url": "https://www.qemu.org/",
        "purpose": "Run foreign-architecture binaries.",
        "why": "Needed for ARM/MIPS/etc. CTF binaries during local triage.",
        "integration": "docker_candidate",
        "install_hint": "Install qemu-user in pwn/reverse container.",
    },
    {
        "name": "IDA Free",
        "categories": ["reverse", "pwn"],
        "url": "https://hex-rays.com/ida-free/",
        "purpose": "Interactive disassembler/decompiler GUI.",
        "why": "Common manual reverse tool; complements optional IDA MCP read-only adapter.",
        "integration": "external_gui_or_mcp",
        "install_hint": "Install separately; configure IDA MCP only when explicitly enabled.",
    },
    {
        "name": "Binary Ninja",
        "categories": ["reverse", "pwn"],
        "url": "https://binary.ninja/",
        "purpose": "Interactive reverse engineering platform.",
        "why": "Manual reverse companion and possible future export adapter target.",
        "integration": "external_gui",
        "install_hint": "Install separately; use exported notes/artifacts.",
    },
    {
        "name": "Cutter",
        "categories": ["reverse", "pwn"],
        "url": "https://github.com/rizinorg/cutter",
        "purpose": "GUI reverse engineering platform built on Rizin.",
        "why": "Open GUI companion for rizin/radare2 workflows.",
        "integration": "external_gui",
        "install_hint": "brew install cutter or download release.",
    },
    {
        "name": "objdump/readelf",
        "categories": ["reverse", "pwn"],
        "url": "https://sourceware.org/binutils/",
        "purpose": "ELF headers, sections, symbols, and disassembly.",
        "why": "Cheap static triage for binary metadata and symbol tables.",
        "integration": "wrapper_candidate",
        "install_hint": "Install binutils.",
    },
    {
        "name": "strace",
        "categories": ["reverse", "pwn"],
        "url": "https://strace.io/",
        "purpose": "Trace system calls.",
        "why": "Useful for reverse tasks where behavior is clearer than static code.",
        "integration": "docker_candidate",
        "install_hint": "Available on Linux; use in reverse container.",
    },
    {
        "name": "ltrace",
        "categories": ["reverse", "pwn"],
        "url": "https://ltrace.org/",
        "purpose": "Trace dynamic library calls.",
        "why": "Useful for strcmp/puts/malloc-style behavioral hints in simple crackmes.",
        "integration": "docker_candidate",
        "install_hint": "Available on Linux; use in reverse container.",
    },
    {
        "name": "UPX",
        "categories": ["reverse", "forensics"],
        "url": "https://github.com/upx/upx",
        "purpose": "Executable packer and unpacker.",
        "why": "Common packed-binary CTF clue and unpacking tool.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install upx",
    },
    {
        "name": "FLOSS",
        "categories": ["reverse", "forensics"],
        "url": "https://github.com/mandiant/flare-floss",
        "purpose": "Extract obfuscated strings from malware and binaries.",
        "why": "Useful after ordinary strings misses encoded/stack strings.",
        "integration": "wrapper_candidate",
        "install_hint": "pipx install flare-floss",
    },
    {
        "name": "capa",
        "categories": ["reverse", "forensics"],
        "url": "https://github.com/mandiant/capa",
        "purpose": "Identify capabilities in executable files.",
        "why": "Useful for malware/reverse CTF triage and high-level behavior hints.",
        "integration": "wrapper_candidate",
        "install_hint": "pipx install flare-capa",
    },
    {
        "name": "JADX",
        "categories": ["reverse", "misc"],
        "url": "https://github.com/skylot/jadx",
        "purpose": "Dex/Android decompiler.",
        "why": "Common for APK reverse challenges.",
        "integration": "external_gui_or_wrapper_candidate",
        "install_hint": "brew install jadx",
    },
    {
        "name": "apktool",
        "categories": ["reverse", "forensics"],
        "url": "https://github.com/iBotPeaches/Apktool",
        "purpose": "Android APK resource decode/rebuild tool.",
        "why": "Useful for Android challenge resources and manifests.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install apktool",
    },
    {
        "name": "Capstone",
        "categories": ["reverse", "pwn"],
        "url": "https://github.com/capstone-engine/capstone",
        "purpose": "Disassembly framework.",
        "why": "Useful library for future binary analyzers and custom architecture helpers.",
        "integration": "library_dependency",
        "install_hint": "pip install capstone",
    },
    {
        "name": "Unicorn",
        "categories": ["reverse", "pwn"],
        "url": "https://github.com/unicorn-engine/unicorn",
        "purpose": "CPU emulator framework.",
        "why": "Useful for emulating validation routines and unpacking snippets.",
        "integration": "library_dependency",
        "install_hint": "pip install unicorn",
    },
    {
        "name": "zbarimg",
        "categories": ["misc", "forensics"],
        "url": "https://github.com/mchehab/zbar",
        "purpose": "Barcode and QR code decoding.",
        "why": "Common misc/forensics QR-code challenge helper.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install zbar",
    },
    {
        "name": "ImageMagick",
        "categories": ["misc", "forensics"],
        "url": "https://github.com/ImageMagick/ImageMagick",
        "purpose": "Image conversion and inspection.",
        "why": "Useful for channel splitting, format conversion, and image puzzle preparation.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install imagemagick",
    },
    {
        "name": "ffmpeg",
        "categories": ["misc", "forensics"],
        "url": "https://github.com/FFmpeg/FFmpeg",
        "purpose": "Audio/video conversion and extraction.",
        "why": "Useful for media, frame extraction, and audio CTF tasks.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install ffmpeg",
    },
    {
        "name": "SoX",
        "categories": ["misc", "forensics"],
        "url": "https://sourceforge.net/projects/sox/",
        "purpose": "Audio processing and conversion.",
        "why": "Useful for waveform, sample-rate, and channel manipulation in audio puzzles.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install sox",
    },
    {
        "name": "Sonic Visualiser",
        "categories": ["misc", "forensics"],
        "url": "https://www.sonicvisualiser.org/",
        "purpose": "Audio spectrogram inspection GUI.",
        "why": "Manual companion for spectrogram and hidden-audio-message tasks.",
        "integration": "external_gui",
        "install_hint": "Install separately.",
    },
    {
        "name": "Tesseract OCR",
        "categories": ["misc", "forensics", "osint"],
        "url": "https://github.com/tesseract-ocr/tesseract",
        "purpose": "Optical character recognition.",
        "why": "Useful for screenshots, QR-adjacent puzzles, and document image text extraction.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install tesseract",
    },
    {
        "name": "jq",
        "categories": ["misc", "web", "forensics"],
        "url": "https://github.com/jqlang/jq",
        "purpose": "JSON processing.",
        "why": "Useful for API responses, logs, and solver-script pipelines.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install jq",
    },
    {
        "name": "ripgrep",
        "categories": ["misc", "forensics", "reverse"],
        "url": "https://github.com/BurntSushi/ripgrep",
        "purpose": "Fast recursive text search.",
        "why": "Useful for source challenges, leaked repos, and extracted artifact trees.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install ripgrep",
    },
    {
        "name": "GitTools",
        "categories": ["misc", "forensics", "web"],
        "url": "https://github.com/internetwache/GitTools",
        "purpose": "Recover and analyze exposed .git directories.",
        "why": "Common web/misc challenge pattern when .git is exposed.",
        "integration": "scoped_active_wrapper_candidate",
        "install_hint": "Use in web tool container with explicit scope.",
    },
    {
        "name": "nmap",
        "categories": ["infra", "web"],
        "url": "https://github.com/nmap/nmap",
        "purpose": "Network service discovery.",
        "why": "Already represented by scoped nmap wrapper; useful for infra-style labs.",
        "integration": "existing_wrapper",
        "install_hint": "brew install nmap",
    },
    {
        "name": "zardus/ctf-tools",
        "categories": ["infra", "misc"],
        "url": "https://github.com/zardus/ctf-tools",
        "purpose": "Broad CTF tool installation scripts and catalog.",
        "why": "Good reference for tool coverage, but ForgeFlag should avoid unreviewed bulk installs.",
        "integration": "reference_only",
        "install_hint": "Use as a reference catalog; port selected tools into explicit wrappers.",
    },
)


def recommended_projects(category: str | None = None) -> list[dict[str, Any]]:
    projects = [dict(project) for project in PROJECT_CATALOG]
    if category:
        projects = [project for project in projects if category in project["categories"]]
    return sorted(projects, key=lambda project: (project["categories"][0], project["name"].lower()))
