from __future__ import annotations

from typing import Any


PROJECT_CATALOG: tuple[dict[str, Any], ...] = (
    {
        "name": "CTFd",
        "categories": ["infra"],
        "url": "https://github.com/CTFd/CTFd",
        "purpose": "CTF platform and scoreboard for Jeopardy-style events.",
        "why": "Widely used event platform; useful for future scoreboard ingestion and challenge sync.",
        "integration": "future_connector",
        "install_hint": "Run as a separate service; integrate through CTFd API rather than local shell wrappers.",
    },
    {
        "name": "pwntools",
        "categories": ["pwn"],
        "url": "https://github.com/Gallopsled/pwntools",
        "purpose": "Python exploit-development and CTF automation framework.",
        "why": "Standard workflow for process/socket interaction, packing, ELF, ROP, shellcraft, and exploit scripts.",
        "integration": "solver_workspace",
        "install_hint": "pip install pwntools",
    },
    {
        "name": "pwndbg",
        "categories": ["pwn", "reverse"],
        "url": "https://github.com/pwndbg/pwndbg",
        "purpose": "GDB plugin focused on exploit development and reverse engineering.",
        "why": "Improves heap/stack/register/context inspection for pwn debugging.",
        "integration": "docker_candidate",
        "install_hint": "Install inside the pwn/reverse tool container with GDB.",
    },
    {
        "name": "GEF",
        "categories": ["pwn", "reverse"],
        "url": "https://github.com/hugsy/gef",
        "purpose": "GDB enhancement plugin for exploit development.",
        "why": "Lightweight alternative or complement to pwndbg for binary debugging.",
        "integration": "docker_candidate",
        "install_hint": "Install inside the pwn/reverse tool container with GDB.",
    },
    {
        "name": "ROPgadget",
        "categories": ["pwn", "reverse"],
        "url": "https://github.com/JonathanSalwan/ROPgadget",
        "purpose": "Search ROP/JOP gadgets in binaries.",
        "why": "Directly supports exploit-chain construction after checksec and crash triage.",
        "integration": "wrapper_candidate",
        "install_hint": "pip install ROPGadget",
    },
    {
        "name": "Ropper",
        "categories": ["pwn", "reverse"],
        "url": "https://github.com/sashs/Ropper",
        "purpose": "Find gadgets and build ROP chains.",
        "why": "Useful second opinion for gadget discovery when ROPgadget misses a pattern.",
        "integration": "wrapper_candidate",
        "install_hint": "pip install ropper",
    },
    {
        "name": "Ghidra",
        "categories": ["reverse", "pwn"],
        "url": "https://github.com/NationalSecurityAgency/ghidra",
        "purpose": "Software reverse engineering suite.",
        "why": "Primary open-source decompiler/disassembler option for reverse and pwn triage.",
        "integration": "external_gui_or_mcp",
        "install_hint": "Install separately; call through export scripts or MCP-style read-only adapters.",
    },
    {
        "name": "radare2",
        "categories": ["reverse", "pwn"],
        "url": "https://github.com/radareorg/radare2",
        "purpose": "Command-line reverse engineering framework.",
        "why": "Scriptable binary analysis fits ForgeFlag wrapper execution better than GUI-only workflows.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install radare2",
    },
    {
        "name": "Rizin",
        "categories": ["reverse", "pwn"],
        "url": "https://github.com/rizinorg/rizin",
        "purpose": "Fork of radare2 focused on maintainable reverse engineering tooling.",
        "why": "Good candidate for scripted reverse workflows and future typed wrappers.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install rizin",
    },
    {
        "name": "angr",
        "categories": ["reverse", "pwn"],
        "url": "https://github.com/angr/angr",
        "purpose": "Binary analysis framework for symbolic execution and program analysis.",
        "why": "Good fit for crackme path solving, symbolic constraints, and reachability analysis.",
        "integration": "solver_workspace",
        "install_hint": "pip install angr",
    },
    {
        "name": "CyberChef",
        "categories": ["crypto", "misc", "forensics"],
        "url": "https://github.com/gchq/CyberChef",
        "purpose": "Encoding, decoding, compression, crypto, and data transformation workbench.",
        "why": "High-value reference for recipe-style transform chains and misc/crypto automation ideas.",
        "integration": "recipe_reference",
        "install_hint": "Use hosted UI or run locally; model recipes as future ForgeFlag transform steps.",
    },
    {
        "name": "RsaCtfTool",
        "categories": ["crypto"],
        "url": "https://github.com/RsaCtfTool/RsaCtfTool",
        "purpose": "RSA weak-key and CTF attack toolkit.",
        "why": "Directly maps to common RSA CTF failure modes and key-parameter triage.",
        "integration": "wrapper_candidate",
        "install_hint": "pip install git+https://github.com/RsaCtfTool/RsaCtfTool.git",
    },
    {
        "name": "Z3",
        "categories": ["crypto", "reverse", "misc"],
        "url": "https://github.com/Z3Prover/z3",
        "purpose": "SMT solver for constraints.",
        "why": "Core dependency for symbolic crypto, crackme constraints, and puzzle solving.",
        "integration": "library_dependency",
        "install_hint": "pip install z3-solver",
    },
    {
        "name": "SageMath",
        "categories": ["crypto"],
        "url": "https://github.com/sagemath/sage",
        "purpose": "Mathematics system for number theory and algebra.",
        "why": "Useful for lattice, finite-field, elliptic-curve, and RSA math-heavy challenges.",
        "integration": "docker_candidate",
        "install_hint": "Use Docker or system package; avoid forcing it into the base Python venv.",
    },
    {
        "name": "Binwalk",
        "categories": ["forensics", "misc"],
        "url": "https://github.com/ReFirmLabs/binwalk",
        "purpose": "Firmware and embedded-file signature scanner.",
        "why": "Already in ForgeFlag; keep as the first broad binary/container triage step.",
        "integration": "existing_wrapper",
        "install_hint": "brew install binwalk",
    },
    {
        "name": "ExifTool",
        "categories": ["forensics", "misc"],
        "url": "https://github.com/exiftool/exiftool",
        "purpose": "Metadata extraction for images and documents.",
        "why": "Already in ForgeFlag; useful for image/document metadata pivots.",
        "integration": "existing_wrapper",
        "install_hint": "brew install exiftool",
    },
    {
        "name": "Volatility 3",
        "categories": ["forensics"],
        "url": "https://github.com/volatilityfoundation/volatility3",
        "purpose": "Memory image analysis framework.",
        "why": "Needed for memory forensics milestone; should live in a heavier tool container.",
        "integration": "docker_candidate",
        "install_hint": "pip install volatility3",
    },
    {
        "name": "Didier Stevens Suite",
        "categories": ["forensics", "misc"],
        "url": "https://github.com/DidierStevens/DidierStevensSuite",
        "purpose": "Document, PDF, OLE, and malware-analysis helper scripts.",
        "why": "Strong coverage for Office/PDF CTF artifacts beyond generic strings/binwalk.",
        "integration": "wrapper_candidate",
        "install_hint": "Install selected scripts in a forensics container.",
    },
    {
        "name": "Wireshark",
        "categories": ["traffic", "forensics"],
        "url": "https://gitlab.com/wireshark/wireshark",
        "purpose": "Packet analysis suite; provides tshark CLI.",
        "why": "ForgeFlag already uses tshark; future traffic work should deepen HTTP/DNS/TCP stream extraction.",
        "integration": "existing_wrapper",
        "install_hint": "brew install wireshark or tshark",
    },
    {
        "name": "Scapy",
        "categories": ["traffic", "misc"],
        "url": "https://github.com/secdev/scapy",
        "purpose": "Python packet manipulation and parsing library.",
        "why": "Good for custom protocol parsing when tshark fields are insufficient.",
        "integration": "library_dependency",
        "install_hint": "pip install scapy",
    },
    {
        "name": "sqlmap",
        "categories": ["web"],
        "url": "https://github.com/sqlmapproject/sqlmap",
        "purpose": "SQL injection detection and exploitation tool.",
        "why": "Useful only behind strict scope controls; should not become default active probing.",
        "integration": "scoped_active_wrapper_candidate",
        "install_hint": "Install in web tool container; require allowed host and active probe.",
    },
    {
        "name": "ffuf",
        "categories": ["web"],
        "url": "https://github.com/ffuf/ffuf",
        "purpose": "Fast web fuzzer for paths, parameters, and virtual hosts.",
        "why": "Good next step for scoped route discovery with request budgets.",
        "integration": "scoped_active_wrapper_candidate",
        "install_hint": "brew install ffuf",
    },
    {
        "name": "nuclei",
        "categories": ["web", "infra"],
        "url": "https://github.com/projectdiscovery/nuclei",
        "purpose": "Template-based vulnerability scanner.",
        "why": "Useful for authorized CTF infrastructure checks, but must be scope-gated.",
        "integration": "scoped_active_wrapper_candidate",
        "install_hint": "brew install nuclei",
    },
    {
        "name": "hashcat",
        "categories": ["crypto", "misc"],
        "url": "https://github.com/hashcat/hashcat",
        "purpose": "Password/hash recovery.",
        "why": "Useful for hash cracking tasks; should be optional because GPU/driver setup varies.",
        "integration": "docker_or_host_tool",
        "install_hint": "brew install hashcat or use host GPU environment.",
    },
    {
        "name": "John the Ripper",
        "categories": ["crypto", "misc"],
        "url": "https://github.com/openwall/john",
        "purpose": "Password/hash recovery suite.",
        "why": "Complements hashcat and works well on CPU-only setups.",
        "integration": "wrapper_candidate",
        "install_hint": "brew install john",
    },
    {
        "name": "zardus/ctf-tools",
        "categories": ["infra", "misc"],
        "url": "https://github.com/zardus/ctf-tools",
        "purpose": "Broad CTF tool installation scripts and catalog.",
        "why": "Good reference for tool coverage, but ForgeFlag should avoid unreviewed bulk installs.",
        "integration": "reference_only",
        "install_hint": "Use as a reference catalog; port selected tools into explicit wrappers.",
    },
)


def recommended_projects(category: str | None = None) -> list[dict[str, Any]]:
    projects = [dict(project) for project in PROJECT_CATALOG]
    if category:
        projects = [project for project in projects if category in project["categories"]]
    return sorted(projects, key=lambda project: (project["categories"][0], project["name"].lower()))
